const policyPages={
  about:{title:'요미위키 소개',lead:'요미위키는 농산물·농축산물·농기계 거래 전에 확인할 기준과 절차를 쉬운 말로 정리하는 독립 지식사전입니다.',sections:[['우리가 다루는 범위','농산물 등급·선별, 보관·출하, 농축산물 이력 확인, 농기계 점검, 거래 용어만 다룹니다.'],['외부 시세·거래 안내','요미위키는 독립 지식사전이며 특정 거래 플랫폼과 제휴하지 않습니다. 시세·매물 확인이 필요한 문맥에서만 해당 안내로 연결합니다.'],['운영 원칙','공식 자료를 우선하고 광고와 편집을 분리하며, 확인되지 않은 가격·등급·안전 정보를 단정하지 않습니다.']]},
  'editorial-policy':{title:'편집 원칙',lead:'현장에서 바로 쓸 수 있는 정확한 기준을 만들기 위한 요미위키의 편집 규칙입니다.',sections:[['공식 근거 우선','농림축산식품부·농촌진흥청·국립농산물품질관리원·축산물이력제 등 1차 자료를 우선 확인합니다.'],['범위와 날짜 표시','지역·품종·시기·거래 규격에 따라 달라지는 내용은 예외를 함께 적고 기준일을 표시합니다.'],['상업적 분리','외부 거래 안내 링크는 유입 측정값을 포함할 수 있지만, 링크가 문서의 결론이나 순위를 바꾸지 않습니다.'],['수정','공식 기준 변경이나 오류 제보가 확인되면 문서와 검수 기록을 수정합니다.']]},
  'review-readiness':{title:'검수 기록',lead:'공개 문서가 검색과 거래 판단에 쓰일 준비가 되었는지 확인하는 항목입니다.',sections:[['2026-08-09 전면 검수','기존 비농업 주제를 사이트맵에서 제외하고 농산물·농축산물·농기계 지식 문서 10개를 새로 구성했습니다.'],['기술 검수','각 문서의 제목·설명·canonical·구조화 데이터·공식 출처·외부 안내 UTM을 확인했습니다.'],['디자인 검수','화이트 테마, 큰 한글 글꼴, 검색 중심 구조, 키보드 입력, 모바일 줄바꿈과 가로 넘침을 점검합니다.']]},
  privacy:{title:'개인정보 처리 안내',lead:'요미위키는 로그인 없이 지식 검색과 문서 열람을 제공합니다.',sections:[['수집 범위','접속 로그와 검색·문서·외부 안내 이동 이벤트 등 서비스 개선에 필요한 최소 이용 정보가 분석 도구에 기록될 수 있습니다.'],['쿠키와 분석','Google Analytics 등 분석 도구가 쿠키를 사용할 수 있습니다. 브라우저 설정에서 쿠키를 제한할 수 있습니다.'],['문의','개인정보 관련 문의는 문의 페이지의 운영 연락처를 통해 접수할 수 있습니다.']]},
  terms:{title:'이용약관',lead:'요미위키 정보는 거래 전 확인을 돕기 위한 참고 자료입니다.',sections:[['정보의 성격','공식 원문과 지역 담당기관 안내가 우선하며, 문서는 법률·세무·수의·정비 전문 판단을 대신하지 않습니다.'],['이용자 책임','거래 당사자는 실제 품목·기계·서류와 최신 규정을 직접 확인해야 합니다.'],['금지 행위','무단 수집으로 서비스를 방해하거나 문서를 사칭·변조해 거래에 사용하는 행위를 금지합니다.']]},
  disclaimer:{title:'면책 안내',lead:'농업 현장 조건과 거래 대상은 매번 다릅니다.',sections:[['변동 가능성','등급·시세·보관·출하·정비 기준은 품종·지역·시기·장비 상태와 공식 기준 개정에 따라 달라질 수 있습니다.'],['실물 확인','요미위키 문서만으로 거래를 확정하지 말고 실물·명판·표시사항·계약서·공식 조회 결과를 확인하세요.']]},
  contact:{title:'문의와 정정 요청',lead:'오류·누락·공식 기준 개정·링크 문제를 알려주시면 확인 후 수정합니다.',sections:[['정정 요청에 포함할 내용','문서 주소, 문제가 되는 문장, 확인 가능한 공식 자료 주소, 수정 이유를 함께 보내주세요.'],['운영 연락처','이메일: consultingjinjeong@gmail.com'],['처리 원칙','광고·매물 등록 문의와 편집 정정 요청을 분리해 처리합니다.']]}
};
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function renderPolicy(path){const p=policyPages[path];if(!p)return null;return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(p.title)} | 요미위키</title><meta name="description" content="${esc(p.lead)}"><meta name="robots" content="index,follow"><link rel="canonical" href="https://yomiwiki.com/${path}"><link rel="stylesheet" href="/knowledge.css?v=3.0.0"></head><body><header class="site-header"><div class="header-inner"><a class="brand" href="/"><strong>요미위키</strong></a><nav class="top-nav"><a href="/knowledge/produce-items">품목</a><a href="/knowledge/produce-grading">등급·선별</a><a href="/knowledge/farm-machinery">농기계</a></nav></div></header><main><nav class="breadcrumb"><a href="/">홈</a><span>›</span><span>운영 정보</span></nav><article><header class="article-head"><p class="article-kicker">요미위키 운영</p><h1>${esc(p.title)}</h1><p>${esc(p.lead)}</p><div class="article-meta"><span>기준일 2026-08-09</span></div></header><div class="article-grid"><div>${p.sections.map((s,i)=>`<section class="content-section"><h2><span>${i+1}</span>${esc(s[0])}</h2><p>${esc(s[1])}</p></section>`).join('')}</div><aside class="rail"><section><h2>운영 정보</h2><nav><a href="/about">소개</a><a href="/editorial-policy">편집 원칙</a><a href="/review-readiness">검수 기록</a><a href="/privacy">개인정보</a><a href="/terms">이용약관</a><a href="/contact">문의</a></nav></section></aside></div></article></main></body></html>`}
