import fs from 'node:fs/promises';
import path from 'node:path';

const root = path.resolve(import.meta.dirname, '..', 'public', 'mn');
const date = '2026-09-24';
const base = 'https://yomiwiki.com/mn';
const esc = value => String(value).replace(/[&<>"']/g, character => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[character]));
const sourceList = sources => `<section class="sources"><h2>Ашигласан эх сурвалж</h2><ul>${sources.map(([title, url]) => `<li><a href="${esc(url)}" rel="noopener noreferrer">${esc(title)}</a></li>`).join('')}</ul><p>Албан эх сурвалж шинэчлэгдэж болно. Бодит ажил, гэрээ хийхийн өмнө тухайн байгууллагын хамгийн сүүлийн мэдээллийг шалгана уу.</p></section>`;
const shell = ({ title, description, slug, body, type = 'Article' }) => {
  const url = slug ? `${base}/${slug}` : `${base}/`;
  const schema = JSON.stringify({ '@context':'https://schema.org', '@type':type, headline:title, description, inLanguage:'mn-MN', datePublished:date, dateModified:date, mainEntityOfPage:url, author:{'@type':'Organization', name:'YomiWiki редакц'}, publisher:{'@type':'Organization', name:'YomiWiki', url:'https://yomiwiki.com/'} }).replace(/</g, '\\u003c');
  return `<!doctype html><html lang="mn"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} | YomiWiki</title><meta name="description" content="${esc(description)}"><meta name="robots" content="index,follow"><link rel="canonical" href="${url}"><meta property="og:type" content="article"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${url}"><link rel="icon" href="/mn/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/mn/style.css"><script type="application/ld+json">${schema}</script></head><body><a class="skip" href="#main">Үндсэн хэсэг рүү очих</a><header class="top"><div class="wrap"><a class="brand" href="/mn/">YomiWiki <span>Монгол</span></a><nav aria-label="Монгол агуулга"><a href="/mn/">Гарын авлага</a><a href="/mn/storage-glossary">Зоорийн нэр томьёо</a><a href="/mn/seed-labels">Үрийн шошго</a><a href="/">한국어</a></nav></div></header><main id="main" class="wrap">${body}</main><footer class="bottom"><div class="wrap"><span>YomiWiki · Шалгах боломжтой хөдөө аж ахуйн тайлбар</span><a href="/about">Сайтын тухай</a><a href="/contact">Алдаа, засвар мэдэгдэх</a></div></footer></body></html>`;
};

const pages = [
  {
    slug:'', title:'Монголын хөдөө аж ахуйн нэр томьёо',
    description:'Хүнсний ногооны зоорь, таримал ургамлын үрийн шошгыг шалгах монгол хэл дээрх хоёр бие даасан гарын авлага.',
    body:`<div class="hero"><p class="eyebrow">Монгол хэл дээрх тайлбар</p><h1>Нэр томьёог ойлгож, баримтыг өөрөө шалгаарай</h1><p>Зоорь, үрийн тухай зар эсвэл бичиг баримт дээрх үгийг нэг утгаар ойлгох нь алдаатай худалдан авалт, хадгалалтын шийдвэрээс сэргийлэх эхний алхам. Энд үнэ, бэлэн бараа, борлуулагчийн амлалт нийтлэхгүй; шалгах асуулт болон эх сурвалж өгнө.</p></div><div class="cards"><a href="/mn/storage-glossary"><small>Хадгалалт</small><h2>Ногооны зоорийн 8 нэр томьёо</h2><p>Агаар сэлгэлт, харьцангуй чийг, дотор температур, багцын бүртгэлийг яаж асуух вэ?</p><span>Тайлбар, бөглөх хуудас →</span></a><a href="/mn/seed-labels"><small>Үр, сорт</small><h2>Үрийн шошго унших 7 алхам</h2><p>Таримлын нэр, сорт, багц, эх үүсвэр, шинжилгээний баримтыг хооронд нь тулгана.</p><span>Шалгах хуудас →</span></a></div><section class="panel"><h2>Энэ цувралын арга</h2><p>Монгол Улсын төрийн байгууллагын нээлттэй эх сурвалжийг эхэлж шалгана. Баримтад буй заалт ба манай тайлбарыг ялгаж бичнэ. Хадгалалтын тохиргоо нь таримал, зоорийн төхөөрөмж, улирал бүрт өөр тул энд нэг температурыг бүх ногоонд тохирно гэж заахгүй.</p><p>Нийтэлсэн ба хамгийн сүүлд шалгасан өдөр: <time datetime="${date}">${date}</time>. Алдаа эсвэл хуучирсан холбоосыг <a href="/contact">засварын хаягаар</a> мэдэгдээрэй.</p></section>`
  },
  {
    slug:'storage-glossary', title:'Ногооны зоорийн нэр томьёо: хадгалалтыг шалгах хуудас',
    description:'Агаар сэлгэлт, чийг, температур, багцын бүртгэл зэрэг хүнсний ногооны зоорийн 8 нэр томьёо ба худалдан авагчийн шалгах асуултууд.',
    body:`<nav class="crumb"><a href="/mn/">Монгол гарын авлага</a> / Хадгалалт</nav><p class="eyebrow">Хадгалалтын тайлбар · ${date}</p><h1>Ногооны зоорийн 8 нэр томьёо</h1><p class="lead">“Зооринд хадгалсан” гэсэн нэг өгүүлбэр нь чанарыг батлахгүй. Төмс, лууван, байцаа зэрэг бүтээгдэхүүний сорт, хураасан өдөр, оруулсан багц, агаар ба чийгийн нөхцөлийг тус тус асууна. Доорх хүснэгт нь зоорийн ажиллагааг шалгах ярианы хуудас юм.</p><div class="table-scroll"><table><caption>Худалдагчаас юу асуух вэ?</caption><thead><tr><th scope="col">Нэр томьёо</th><th scope="col">Утга</th><th scope="col">Шалгах асуулт</th></tr></thead><tbody><tr><th scope="row">Зоорь</th><td>Бүтээгдэхүүнийг хадгалах зориулалттай байр.</td><td>Ямар төрлийн зоорь вэ; халаалт, хөргөлт бий юу?</td></tr><tr><th scope="row">Агаар сэлгэлт</th><td>Дотор ба гаднах агаарын солилцоо.</td><td>Агаар оруулах, гаргах төхөөрөмж ажиллаж байна уу?</td></tr><tr><th scope="row">Харьцангуй чийг</th><td>Агаар дахь усны уурын хэмжээг илэрхийлэх үзүүлэлт.</td><td>Чийгийг юугаар, хаана хэмждэг; бүртгэл бий юу?</td></tr><tr><th scope="row">Дотор температур</th><td>Зоорийн хэмжсэн дулаан.</td><td>Хэмжигчийн байрлал, өдөр тутмын тэмдэглэл байна уу?</td></tr><tr><th scope="row">Бүтээгдэхүүний температур</th><td>Ногооны өөрийнх нь дулаан; өрөөний агаартай заавал ижил биш.</td><td>Ачааг оруулах, гаргах үед зөрүүг шалгасан уу?</td></tr><tr><th scope="row">Багц</th><td>Ижил эх үүсвэр, хугацаатай хадгалж буй хэсэг.</td><td>Багц бүрийн хураалт, оруулсан өдрийг ялгасан уу?</td></tr><tr><th scope="row">Конденсац</th><td>Хүйтэн гадаргуу дээр тогтсон усны дусал.</td><td>Тааз, хананд ус тогтох эсэхийг үзсэн үү?</td></tr><tr><th scope="row">Ялгалт</th><td>Гэмтсэн, ялзарсан эсвэл өөр багцын ногоог тусгаарлах ажил.</td><td>Сүүлийн шалгалтаар хэдийг салгасан бэ?</td></tr></tbody></table></div><section class="panel"><h2>Очихоос өмнө бичиж авах дөрвөн зүйл</h2><ol><li>Таримлын нэр, сорт, хураалтын өдөр, жин.</li><li>Зооринд оруулсан өдөр ба багцын дугаар.</li><li>Температур, чийгийн бодит тэмдэглэл болон хэмжсэн газар.</li><li>Гэмтэл, ялзрал, буцаах нөхцөлийг хэнтэй тохирсон нь.</li></ol><p>Энэ бол гэрээ эсвэл чанарын гэрчилгээ биш. Таримал бүрийн тохирох горимыг холбогдох стандарт, мэргэжлийн заавраас нэмж шалгана.</p></section>${sourceList([['ХХААХҮЯ-ны төмс, хүнсний ногооны зоорийн хяналтын асуулга (MNS 3024-2020-ийг дурдсан)','https://mofa.gov.mn/files/pdf-files/6h4b1thvnum/643cb8bca8f132494e96ca3d.pdf'],['Ургамлын гаралтай хүнсний бүтээгдэхүүний ул мөрийг мөрдөн тогтоох бүртгэлийн журам','https://legalinfo.mn/mn/detail?lawId=206926']])}<p class="next"><a href="/mn/seed-labels">Үрийн шошго шалгах хуудас →</a></p>`
  },
  {
    slug:'seed-labels', title:'Таримал ургамлын үрийн шошго: худалдан авахын өмнөх 7 шалгалт',
    description:'Таримал ургамлын үр, сорт, багц, эх үүсвэр, шинжилгээний баримтыг тулгаж унших монгол хэл дээрх практик шалгах хуудас.',
    body:`<nav class="crumb"><a href="/mn/">Монгол гарын авлага</a> / Үр, сорт</nav><p class="eyebrow">Үрийн баримт шалгах · ${date}</p><h1>Үрийн шошгыг 7 алхмаар унших нь</h1><p class="lead">“Сайн үр” гэсэн зарын үгнээс илүү тодорхой мэдээлэл хэрэгтэй. Таримлын нэр, сорт, багцын мэдээлэл, гарал үүсэл болон чанарыг нотлох баримтыг нэг нэгээр нь тулгаж үзээрэй. Доорх жагсаалт нь албан ёсны баталгаажуулалт биш, худалдан авагчийн өөрийн шалгах дараалал юм.</p><ol class="steps"><li><strong>Зориулалтыг тодруулах.</strong> Тарих үр үү, хүнсэнд хэрэглэх үр тариа юу гэдгийг эхэлж ялга. Энэ хоёрын шаардлага ижил биш.</li><li><strong>Таримал ба сортын нэрийг тэмдэглэх.</strong> Зар, уутны шошго, дагалдах баримтад ижил нэр бичсэн эсэхийг харьцуул.</li><li><strong>Багц, жинг тулгах.</strong> Нэг нэртэй олон багцыг хольж ойлгохгүйн тулд багцын тэмдэглэгээ, савлагааны жин, нийлүүлэх тоо хэмжээг бич.</li><li><strong>Гарал үүслийг асуух.</strong> Үйлдвэрлэсэн эсвэл импортолсон эх үүсвэр нь тодорхой юу; худалдагч баримтаа үзүүлж чадах уу?</li><li><strong>Шинжилгээ ба баталгааны баримт шалгах.</strong> Баримтын дугаар, огноо, аль багцад хамаарахыг тулга. Зөвхөн зураг харснаар хүчинтэй эсэхийг бүү дүгнэ.</li><li><strong>Хадгалалтын нөхцөл асуух.</strong> Савлагаа бүтэн эсэх, чийгтсэн эсэх, хаана хэр удаан хадгалсныг тодруул. Нөхцөлийг тухайн таримлын заавартай харьцуул.</li><li><strong>Тохиролцоог бичгээр үлдээх.</strong> Сорт, багц, жин, үнэ, хүргэлт, буцаалт, илэрсэн зөрүүг хэрхэн шийдэхийг нэг баримтад оруул.</li></ol><section class="panel"><h2>Шошго ба зар зөрвөл</h2><p>Зарын зураг хуучин байж болно. Бодит савлагааны шошго, тухайн багцын баримтын зургийг шинээр авч, дугаарыг тулгатал төлбөрийг түр хойшлуул. Баримтын хүчинтэй байдал эсвэл заавал шаардагдах хэлбэрийн талаар эргэлзвэл эрх бүхий байгууллагаас тодруулна.</p><p>Монгол Улсын таримал ургамлын үр, сортын тухай хуулиар үрийн чанар, гарал үүсэл, хяналттай холбоотой зохицуулалт бий. Энэ хуудас хуулийн бүх шаардлагыг орлохгүй.</p></section>${sourceList([['Таримал ургамлын үр, сортын тухай хууль — legalinfo.mn','https://legalinfo.mn/mn/detail?lawId=16389901659821'],['Таримал ургамлын үр, сортын чанарт тавих улсын хяналтын дүрэм — legalinfo.mn','https://legalinfo.mn/mn/detail?lawId=200768']])}<p class="next"><a href="/mn/storage-glossary">Зоорийн нэр томьёо руу →</a></p>`
  }
];

await fs.mkdir(root, { recursive: true });
for (const page of pages) {
  await fs.writeFile(path.join(root, page.slug ? `${page.slug}.html` : 'index.html'), shell(page), 'utf8');
}
console.log(`built YomiWiki Mongolian hub and ${pages.length - 1} resources`);
